name: Deploy Production to SNUH naver cloud
on:
  schedule:
    - cron: "* * * * *"

jobs:
  deploy:
    name: Deploy - SNUH prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check commit history within last 7 days
        run: |
          echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)";
          echo "$(date -u +%s)";
          echo "$(( $(date -u +%s) - 7*24*60*60 ))";
          echo "$(date -u -r $(( $(date -u +%s) - 7*24*60*60 )) +%Y-%m-%dT%H:%M:%SZ)";
          echo "$(git log --since=$(date -u -r $(( $(date -u +%s) - 7*24*60*60 )) +%Y-%m-%dT%H:%M:%SZ) --oneline)";
          git log --since=$(date -u -r $(( $(date -u +%s) - 7*24*60*60 )) +%Y-%m-%dT%H:%M:%SZ) --oneline;
          if [ "$(git log --since=$(date -u -r $(( $(date -u +%s) - 7*24*60*60 )) +%Y-%m-%dT%H:%M:%SZ) --oneline)" ]; then
            echo "Commits found in the last 7 days. Triggering deployment..."
          else
            echo "No commits in the last 7 days. Skipping deployment."
            exit 78
          fi

      - name: After checking process
        run: echo "After checking process.. my deployment process running here..."
