name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  deploy:
    name: cici
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get version of package.json
        run: |
          version=$(node -p "require('./package.json').version")
          echo "CURRENT_VERSION=$version" >> $GITHUB_ENV

      - name: Get commit messages
        run: |
          echo "${{ github.event.head_commit.message }}"
          echo '${{toJSON(github.event)}}'

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v9.0.31
        with:
          commit-message: ${{ github.event.head_commit.message }}

      - name: Get version of package.json2
        run: |
          version=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$version" >> $GITHUB_ENV
