name: Wiki-Detector
on:
  pull_request:
    branches:
      - develop

jobs:
  detect_wiki_link:
    if: (startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'Feat')) && github.event.label.name == 'feature'
    name: detect-wiki
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "IS_MASTER=$(echo ${{ github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'master' }})" >> $GITHUB_ENV
          echo "LINK=https://github.com/${GITHUB_REPOSITORY}/wiki" >> $GITHUB_ENV
    
      - name: Check pull request message for wiki link
        if: env.IS_MASTER == 'false'
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.body) }}
        run: |
          HAS_WIKI=$(echo ${{contains(env.PR_COMMENTS, env.LINK)}})
          echo "Does the PR message include a wiki link? $HAS_WIKI"
          if [[ $HAS_WIKI == true ]]; then exit 0; else exit 1; fi
