name: Wiki-Detector2
on:
  pull_request:
    branches:
      - develop

jobs:
  detect_wiki_link:
    if: (startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'Feat'))
    name: detect-wiki
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo "LINK=https://github.com/${GITHUB_REPOSITORY}/wiki" >> $GITHUB_ENV
          labels=()
          echo "${{ github.event.pull_request.labels }}"
          for label in ${{ github.event.pull_request.labels }}; do
            echo $label
            echo "${label[0]}"
            labels+=($label[name])
            echo "${labels[@]}"
          done
          echo "LABELS=$labels" >> $GITHUB_ENV
    
      - name: Check pull request message for wiki link
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.body) }}
        run: |
          IS_FEATURE=$(echo ${{contains(env.LABELS, 'feature')}})
          echo "is feature $IS_FEATURE"
          HAS_WIKI=$(echo ${{contains(env.PR_COMMENTS, env.LINK)}})
          echo "Does the PR message include a wiki link? $HAS_WIKI"
          if [[ $HAS_WIKI == true ]]; then exit 0; else exit 1; fi
