name: Wiki-Detector
on:
  pull_request_target:
    branches:
      - develop

jobs:
  detect_wiki_link:

    name: detect-wiki
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request message body
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.body) }}
        run: |
          echo "${GITHUB_REPOSITORY#*/}"
          echo "${GITHUB_REPOSITORY}"
          echo "${{github.head_ref}}"
          echo "${{startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'Feat')}}"
          echo "${{contains(github.head_ref, fromJSON('["feat", "Feat"]'))}}"
          echo "${{ github.event.pull_request.body }}"
          echo "${PR_COMMENTS}"
          echo "${{ contains(github.event.pull_request.body, 'https://github.com/3billion/${GITHUB_REPOSITORY#*/}/wiki/')}}"
      
