name: Wiki-Detector
on:
  pull_request_target:
    types:
      - opened
    branches:
      - develop

jobs:
  detect_wiki_link:
    name: detect
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request message body
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.issue.pull_request) }}
        run: |
          echo "${{ github.event.issue.pull_request }}"
          echo "${PR_COMMENTS}"
          echo "${PR_COMMENTS}" | jq '. [] | .body'
      
