name: Wiki-Detector
on:
  pull_request_target:
    types:
      - opened
    branches:
      - develop

jobs:
  detect_wiki_link:

    name: detect-wiki
    runs-on: ubuntu-latest
    steps:
      - name: Get pull request message body
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.body) }}
        run: |
          echo "${{contains(fromJSON('["feat", "Feat"]'), github.head_ref)}}"
          echo "${{ github.event.pull_request.body }}"
          echo "${PR_COMMENTS}"
          echo "${PR_COMMENTS}" | jq '. [] | .body'
      
