name: Wiki-Detector2
on:
  pull_request:
    branches:
      - develop

jobs:
  detect_wiki_link:
    if: (startsWith(github.head_ref, 'feat') || startsWith(github.head_ref, 'Feat'))
    name: detect-wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        env:
          PR_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "LINK=https://github.com/${GITHUB_REPOSITORY}/wiki" >> $GITHUB_ENV
          gh pr view \
            --json labels \
            --jq '.labels[].name | select("feature")' "$PR_NUMBER"
    
      - name: Check pull request message for wiki link
        env: 
          PR_COMMENTS: ${{ toJSON(github.event.pull_request.body) }}
        run: |
          IS_FEATURE=$(echo ${{contains(env.LABELS, 'feature')}})
          echo "is feature $IS_FEATURE"
          HAS_WIKI=$(echo ${{contains(env.PR_COMMENTS, env.LINK)}})
          echo "Does the PR message include a wiki link? $HAS_WIKI"
          if [[ $HAS_WIKI == true ]]; then exit 0; else exit 1; fi
